!function(){'use strict';var e='products.json',t=280,n=24,a=15e3,r={Pets:'🐾','Car Accessories':'🚗','Home & Kitchen':'🍳','Beauty & Personal Care':'💄',Fitness:'🏋️','Fitness & Gadgets':'🏋️','Tech & Phone Gadgets':'📱','Baby & Kids':'🍼','Health & Wellness':'🌿','Fashion Accessories & Jewelry':'💍','Home Office & Study':'🖊️','Outdoor & Travel':'🏕️','Toys & Games':'🧸'},i={
ext:'M14 4h6v6M20 4l-9 9M18 14v5a1 1 0 0 1-1 1H5a1 1 0 0 1-1-1V7a1 1 0 0 1 1-1h5',star:'M12 3.5l2.6 5.3 5.9.9-4.3 4.1 1 5.8L12 16.9l-5.2 2.7 1-5.8-4.3-4.1 5.9-.9z',share:'M4 12v7a1 1 0 0 0 1 1h14a1 1 0 0 0 1-1v-7M12 3v12M7.5 7.5 12 3l4.5 4.5',x:'M6 6l12 12M18 6 6 18',left:'M15 5l-7 7 7 7',right:'M9 5l7 7-7 7',check:'M20 6 9 17l-5-5',info:'M12 8h.01M11 12h1v5h1M12 21a9 9 0 1 0 0-18 9 9 0 0 0 0 18z'
},o=function(e,t){return(t||document).querySelector(e)},s={all:[],byKey:{},market:'all',niche:'all',day:'latest',sort:'score',q:'',verdict:'all',trend:'all',comp:'all',proof:'all',markup:0,photo:!1,savedOnly:!1,saved:new Set,trendsOn:!1,limit:n,latest:'',updated:'',view:[],current:-1,lastFocus:null};function l(e,t){try{if(void 0===t)return localStorage.getItem(e);localStorage.setItem(e,t)
}catch(e){return null}return null}function c(e){if('string'!=typeof e||e.length>2048)return null;try{var t=new URL(e.trim());return'https:'===t.protocol?t.href:null}catch(e){return null}}function u(e){if('string'!=typeof e||e.length>2048)return null;try{var t=new URL(e.trim());return'https:'===t.protocol||'http:'===t.protocol?t.href:null}catch(e){return null}}function d(e,t){
return String(null==e?'':e).replace(/\s+/g,' ').trim().slice(0,t||300)}function p(e){if('number'==typeof e)return isFinite(e)?e:null;var t=parseFloat(String(null==e?'':e).replace(/[^0-9.\-]/g,''));return isFinite(t)?t:null}function h(e,t){for(var n=d(e,40).split(/[\s,/]/)[0].toLowerCase(),a=0;a<t.length;a++)if(t[a].toLowerCase()===n)return t[a];return''}function f(e,t){
var n=document.createElement(e);t&&Object.keys(t).forEach(function(e){var a=t[e];if(null!=a&&!1!==a)if('class'===e)n.className=a;else if('text'===e)n.textContent=a;else if('vars'===e)Object.keys(a).forEach(function(e){n.style.setProperty(e,a[e])});else if('on'===e.slice(0,2))n.addEventListener(e.slice(2),a);else if('href'===e||'src'===e){var r=/^(#|\.\/|[a-z0-9-]+\.html)/i.test(a)?a:c(a)
;r&&n.setAttribute(e,r)}else n.setAttribute(e,!0===a?'':String(a))});for(var a=2;a<arguments.length;a++)m(n,arguments[a]);return n}function m(e,t){null!=t&&!1!==t&&(Array.isArray(t)?t.forEach(function(t){m(e,t)}):e.appendChild(t instanceof Node?t:document.createTextNode(String(t))))}function v(e){var t=document.createElementNS('http://www.w3.org/2000/svg','svg')
;t.setAttribute('viewBox','0 0 24 24'),t.setAttribute('aria-hidden','true'),t.setAttribute('focusable','false');var n=document.createElementNS('http://www.w3.org/2000/svg','path');return n.setAttribute('d',i[e]),n.setAttribute('fill','none'),n.setAttribute('stroke','currentColor'),n.setAttribute('stroke-width','2'),n.setAttribute('stroke-linecap','round'),n.setAttribute('stroke-linejoin','round'),
t.appendChild(n),t}function y(e,t,n){var a=c(e);return a?f('a',{href:a,target:'_blank',rel:'noopener noreferrer nofollow',class:n||null},t,' ',v('ext'),f('span',{class:'sr-only',text:'(opens in a new tab)'})):null}function g(e,t){var n='Pakistan'===d((e=e&&'object'==typeof e?e:{}).market,20)?'Pakistan':'Global',a=p(e.cost),r=p(e.price),i=p(e.markup);!(i>0)&&a>0&&r>0&&(i=r/a)
;var o=String(e.date||'').slice(0,10),s=function(e){var t='',n=(e=d(e,700)).match(/^Proof:\s*([^·|]+)[·|]\s*/i);if(n){var a=n[1].toLowerCase();t=/sales/.test(a)?'hard':/popular/.test(a)?'popular':/opinion/.test(a)?'opinion':'',e=e.slice(n[0].length)}var r=[];return e.split(/[,;]/).forEach(function(e){
var t=e.trim().match(/^([A-Za-z][A-Za-z &'\-\/()]{1,38}?)\s*[:=]?\s*(\d{1,2}(?:\.\d)?)(?:\s*\/\s*10)?$/);if(t){var n=parseFloat(t[2]);n>=0&&n<=10&&r.push([t[1].trim(),n])}}),{level:t,parts:r.slice(0,10)}}(e.scoreDetails);return{i:t,name:d(e.name,120),market:n,niche:d(e.niche,60)||'Other',score:Math.max(0,Math.min(100,Math.round(p(e.score)||0))),cost:a>0?a:null,price:r>0?r:null,
markup:i>0&&i<1e3?i:null,currency:'Pakistan'===n?'PKR':'USD',competition:h(e.competition,['Low','Medium','High']),trend:h(e.trend,['Hot','Rising','Stable','Falling']),why:d(e.why,600),audience:d(e.audience,300),adIdea:d(e.adIdea,300),whereToSell:d(e.whereToSell,300),risk:d(e.risk,300),keyword:d(e.keyword,80),source:c(e.source),image:u(e.image),imgDirect:!!c(e.image),supplier:c(e.supplier),
date:/^\d{4}-\d{2}-\d{2}$/.test(o)?o:'',proof:s.level,parts:s.parts}}function b(e){return e>=80?{id:'win',label:'Winner',c:'var(--accent)'}:e>=65?{id:'pro',label:'Promising',c:'var(--ink-3)'}:{id:'watch',label:'Watch',c:'var(--bad)'}}function w(e,t){return null==e?'—':'PKR'===t?'Rs '+Math.round(e).toLocaleString('en-US'):'$'+(e>=100?Math.round(e).toLocaleString('en-US'):e.toFixed(2))}
function k(e,t){if(!e)return'—';var n=new Date(e+'T00:00:00');return isNaN(n)?e:n.toLocaleDateString('en-GB',t?{weekday:'long',day:'numeric',month:'long'}:{day:'numeric',month:'short'})}function x(e){return(e.price||0)/('PKR'===e.currency?t:1)}function S(e){if(e.supplier)return e.supplier;var t=encodeURIComponent(e.keyword||e.name)
;return'Pakistan'===e.market?'https://www.daraz.pk/catalog/?q='+t:'https://www.aliexpress.com/wholesale?SearchText='+t}function C(e,t){var n=d(e.keyword||e.name,80),a={comparisonItem:[{keyword:n,geo:t,time:'today 12-m'}],category:0,property:''},r='q='+encodeURIComponent(n)+(t?'&geo='+t:'')+'&date='+encodeURIComponent('today 12-m')+'&hl=en';return{kw:n,
embed:'https://trends.google.com/trends/embed/explore/TIMESERIES?req='+encodeURIComponent(JSON.stringify(a))+'&tz='+(new Date).getTimezoneOffset()+'&hl=en&eq='+encodeURIComponent(r),explore:'https://trends.google.com/trends/explore?'+r}}function A(e,t,n){return'https://images.weserv.nl/?url='+encodeURIComponent(e)+'&w='+t+'&h='+n+'&fit=cover&output=webp&q=76&we'}function T(e){return f('span',{
class:'ph','aria-hidden':'true'},f('span',null,f('b',{text:r[e.niche]||'📦'}),f('small',{text:e.niche})))}function L(e,t,n,a){if(!e.image)return null;var r=f('img',{src:A(e.image,t,n),alt:e.name,loading:'lazy',decoding:'async',referrerpolicy:'no-referrer',width:t,height:n}),i=!1;return r.addEventListener('error',function(){if(!i&&e.imgDirect)return i=!0,void(r.src=e.image);a(r)}),r}
function E(e,t){var n=b(e.score);return f('span',{class:'ring '+(t||''),role:'img','aria-label':'Score '+e.score+' out of 100',vars:{'--v':String(e.score),'--c':n.c}},f('span',{text:String(e.score)}))}function P(e){return'hard'===e.proof?f('span',{class:'pill c-good',title:'The search showed real sales numbers'},v('check'),'Sales proof'):'popular'===e.proof?f('span',{class:'pill c-plain',
title:'Listed as popular, no sales numbers'},'Listed popular'):'opinion'===e.proof?f('span',{class:'pill c-warn',title:'Only opinion, no proof'},'Opinion only'):null}function O(e){return e?f('span',{class:'pill '+('Low'===e?'c-good':'Medium'===e?'c-warn':'c-bad')},e+' competition'):null}function M(e){return e?f('span',{
class:'pill '+('Hot'===e||'Rising'===e?'c-good':'Falling'===e?'c-bad':'c-plain')},('Hot'===e?'🔥 ':'Rising'===e?'📈 ':'')+e):null}function R(e){return f('span',{class:'pill '+e.market},'Pakistan'===e.market?'🇵🇰 Pakistan':'🌍 Global')}function I(e,t){var n=s.saved.has(e.key);return f('button',{class:'btn '+(t?'sm icon':'sm'),type:'button','aria-pressed':String(n),'data-save':e.key,
'aria-label':(n?'Remove from saved: ':'Save: ')+e.name,title:n?'Saved':'Save'},v('star'),t?null:n?'Saved':'Save')}function N(){var e=function(){if(s.savedOnly)return s.all.filter(function(e){return s.saved.has(e.key)});var e=s.all;if('latest'===s.day){var t={};e.forEach(function(e){var n=e.market+'|'+e.niche;(!t[n]||e.date>t[n])&&(t[n]=e.date)}),e=e.filter(function(e){
return t[e.market+'|'+e.niche]===e.date})}else'all'!==s.day&&(e=e.filter(function(e){return e.date===s.day}));return'all'!==s.market&&(e=e.filter(function(e){return e.market===s.market})),'all'!==s.verdict&&(e=e.filter(function(e){return b(e.score).label===s.verdict})),'all'!==s.trend&&(e=e.filter(function(e){return e.trend===s.trend})),'all'!==s.comp&&(e=e.filter(function(e){
return e.competition===s.comp})),'all'!==s.proof&&(e=e.filter(function(e){return e.proof===s.proof})),s.markup&&(e=e.filter(function(e){return(e.markup||0)>=s.markup})),s.photo&&(e=e.filter(function(e){return!!e.image})),e}(),t=function(e){var t=s.q.trim().toLowerCase(),n=e.filter(function(e){
return!('all'!==s.niche&&e.niche!==s.niche||t&&-1===(e.name+' '+e.niche+' '+e.why+' '+e.keyword+' '+e.audience).toLowerCase().indexOf(t))}),a=function(e){return{Low:0,Medium:1,High:2}[e]??3},r={score:function(e,t){return t.score-e.score},markup:function(e,t){return(t.markup||0)-(e.markup||0)||t.score-e.score},competition:function(e,t){return a(e.competition)-a(t.competition)||t.score-e.score},
price:function(e,t){return x(e)-x(t)||t.score-e.score},new:function(e,t){return t.date.localeCompare(e.date)||t.score-e.score}}[s.sort]||function(e,t){return t.score-e.score};return n.sort(r)}(e);s.view=t,function(e){var t=e.filter(function(e){return e.score>=80}).length,n=new Set(e.map(function(e){return e.niche})).size;o('#kpiProducts').textContent=String(e.length),
o('#kpiWinners').textContent=String(t),o('#kpiNiches').textContent=String(n);var a=s.updated;o('#kpiUpdated').textContent=a&&a.slice(11,16)||'—',o('#kpiUpdatedSub').textContent=a?k(a.slice(0,10),!0):'Waiting for data',o('#liveText').textContent=a?'Live · updated '+k(a.slice(0,10))+', '+a.slice(11,16)+' PKT':'Live'}(s.savedOnly?t:e),function(e){var t={};e.forEach(function(e){
t[e.niche]=(t[e.niche]||0)+1}),'all'===s.niche||t[s.niche]||(s.niche='all');var n=o('#niches');n.textContent='',m(n,f('button',{class:'nchip',type:'button','data-niche':'all','aria-pressed':String('all'===s.niche)},'All niches',f('span',{class:'n',text:String(e.length)}))),Object.keys(t).sort().forEach(function(e){m(n,f('button',{class:'nchip',type:'button','data-niche':e,
'aria-pressed':String(s.niche===e)},(r[e]?r[e]+' ':'')+e,f('span',{class:'n',text:String(t[e])})))})}(e),function(e){var t=o('#picksWrap'),n=o('#picks'),a=!s.savedOnly&&'all'===s.niche&&!s.q.trim()&&e.length>4;t.hidden=!a,a&&(n.textContent='',e.slice().sort(function(e,t){return t.score-e.score}).slice(0,4).forEach(function(e){var t=f('span',{class:'th','aria-hidden':'true'})
;m(t,L(e,120,120,function(t){t.replaceWith(document.createTextNode(r[e.niche]||'📦'))})||r[e.niche]||'📦'),m(n,f('button',{class:'pick',type:'button','data-open':e.key},t,f('span',{class:'t'},f('b',{text:e.name}),f('small',{text:('Pakistan'===e.market?'🇵🇰 ':'🌍 ')+w(e.cost,e.currency)+' → '+w(e.price,e.currency)})),f('span',{class:'sc','aria-label':'Score '+e.score,text:String(e.score)})))}))
}(e);var n=o('#list');n.textContent='',n.classList.remove('list-min'),n.setAttribute('aria-busy','false');var a=['all'!==s.verdict,'all'!==s.trend,'all'!==s.comp,'all'!==s.proof,s.markup>0,s.photo,'latest'!==s.day].filter(Boolean).length;o('#fcount').textContent=a?'('+a+')':'',o('#savedCount').textContent=String(s.saved.size),o('#savedCount').hidden=!s.saved.size,
o('#savedBtn').setAttribute('aria-pressed',String(s.savedOnly));var i=s.savedOnly?'saved':'latest'===s.day?'latest hunt per niche':'all'===s.day?'all recent days':k(s.day,!0);if(o('#count').textContent=t.length+(1===t.length?' product':' products')+' · '+i,!t.length)return m(n,s.savedOnly?f('div',{class:'empty'},f('h3',{text:'No saved products yet'}),f('p',{class:'muted',
text:'Press the star on any product to keep it here. Saved items stay in this browser only.'})):f('div',{class:'empty'},f('h3',{text:'Nothing matches'}),f('p',{class:'muted',text:'Try another market, niche or filter.'}),f('button',{class:'btn',type:'button','data-clear':'1',text:'Clear all filters'}))),void(o('#moreRow').hidden=!0);var l=f('div',{class:'grid'})
;t.slice(0,s.limit).forEach(function(e){m(l,function(e){var t=b(e.score),n=f('span',{class:'frame'}),a=f('button',{class:'media',type:'button',tabindex:'-1','aria-hidden':'true','data-open':e.key},n),r=L(e,640,480,function(t){a.classList.add('noimg'),t.replaceWith(T(e))});return r?m(n,r):(a.classList.add('noimg'),m(n,T(e))),m(a,f('span',{class:'tags'},R(e),e.date===s.latest?f('span',{
class:'pill new',text:'New'}):null)),m(a,E(e)),f('article',{class:'card','aria-labelledby':'t-'+e.key},a,f('div',{class:'body'},f('div',{class:'meta'},f('span',{class:'tier '+t.id,text:t.label}),f('span',{'aria-hidden':'true',text:'·'}),f('span',{text:e.niche}),f('span',{'aria-hidden':'true',text:'·'}),f('span',{text:k(e.date)})),f('h3',{class:'title',id:'t-'+e.key},f('button',{type:'button',
'data-open':e.key,text:e.name})),f('div',{class:'econ'},f('div',null,f('span',{text:'Cost'}),f('b',{text:w(e.cost,e.currency)})),f('div',null,f('span',{text:'Sell at'}),f('b',{text:w(e.price,e.currency)})),f('div',null,f('span',{text:'Markup'}),f('b',{text:e.markup?e.markup.toFixed(1)+'×':'—'}))),f('div',{class:'chips'},P(e),O(e.competition),M(e.trend)),e.why?f('p',{class:'why',text:e.why
}):null,f('div',{class:'actions'},f('button',{class:'btn sm grow',type:'button','data-open':e.key,'aria-label':'Details: '+e.name},'Details'),y(S(e),'Pakistan'===e.market?'Daraz':'Supplier','btn primary sm grow'),I(e,!0))))}(e))}),m(n,l);var c=t.length-s.limit;o('#moreRow').hidden=c<=0,c>0&&(o('#moreBtn').textContent='Show more ('+c+' left)')}var F,z,W=o('#detail');function D(e){
var t=b(e.score),n=f('div',{class:'d-media'});m(n,L(e,900,900,function(t){t.replaceWith(T(e))})||T(e))
;var a='hard'===e.proof?'Backed by real sales numbers in today\'s search.':'popular'===e.proof?'Listed as popular, but no sales numbers. Score is capped at 79.':'opinion'===e.proof?'Only opinion found. Score is capped at 69.':'Scored by AI from public web results.',i=null!=e.price&&null!=e.cost?e.price-e.cost:null,o=encodeURIComponent(e.keyword||e.name),l=[y(S(e),'Pakistan'===e.market?'Find on Daraz':'Find supplier','btn primary sm'),y(e.source,'Source')]
;'Pakistan'===e.market?l.push(y('https://www.aliexpress.com/wholesale?SearchText='+o,'AliExpress'),y('https://www.tiktok.com/search?q='+o,'TikTok')):l.push(y('https://www.amazon.com/s?k='+o,'Amazon'),y('https://www.tiktok.com/search?q='+o,'TikTok'));var c=[['Who buys it',e.audience],['Video ad idea',e.adIdea],['Where to sell',e.whereToSell],['Watch out',e.risk]].filter(function(e){return e[1]
}),u=s.view.indexOf(e);return f('div',{class:'d-grid'},n,f('div',{class:'d-body'},f('div',{class:'d-head'},f('div',{class:'chips'},R(e),f('span',{class:'pill c-plain',text:(r[e.niche]?r[e.niche]+' ':'')+e.niche}),f('span',{class:'pill c-plain',text:'Found '+k(e.date)}),e.date===s.latest?f('span',{class:'pill new',text:'New'}):null),f('h2',{id:'d-title',text:e.name})),f('div',{class:'d-score'
},E(e),f('div',null,f('b',{class:'tier '+t.id,text:t.label+' · '+e.score+'/100'}),f('p',{text:a}))),f('div',{class:'econ'},f('div',null,f('span',{text:'Cost'}),f('b',{text:w(e.cost,e.currency)})),f('div',null,f('span',{text:'Sell at'}),f('b',{text:w(e.price,e.currency)})),f('div',null,f('span',{text:null!=i?'Profit / unit':'Markup'}),f('b',{
text:null!=i?w(i,e.currency)+(e.markup?' · '+e.markup.toFixed(1)+'×':''):'—'}))),f('div',{class:'chips'},P(e),O(e.competition),M(e.trend)),e.why?f('section',{class:'d-sec'},f('h3',{text:'Why it can win'}),f('p',{text:e.why})):null,e.parts.length?f('section',{class:'d-sec'},f('h3',{text:'Score breakdown (0–10)'}),f('div',{class:'bars',role:'list'},e.parts.map(function(e){return f('div',{
class:'bar',role:'listitem','aria-label':e[0]+': '+e[1]+' out of 10'},f('span',{class:'lab',text:e[0],'aria-hidden':'true'}),f('span',{class:'track','aria-hidden':'true'},f('span',{class:'fill',vars:{'--w':String(10*e[1])}})),f('span',{class:'val',text:String(e[1]),'aria-hidden':'true'}))}))):null,function(e){var t='Pakistan'===e.market?'PK':'',n=f('div',{class:'tr-box'}),a=f('a',{class:'tr-open',
target:'_blank',rel:'noopener noreferrer nofollow'}),r=[['PK','🇵🇰 Pakistan'],['','🌍 Worldwide']].map(function(e){return f('button',{type:'button','aria-pressed':String(e[0]===t),onclick:function(){t!==e[0]&&(t=e[0],r.forEach(function(e,n){e.setAttribute('aria-pressed',String((0===n?'PK':'')===t))}),o())}},e[1])});function i(){s.trendsOn=!0;var a=C(e,t);n.textContent='',n.className='tr-box on',
m(n,f('iframe',{class:'tr-frame',src:a.embed,title:'Google Trends chart for '+a.kw+(t?' in Pakistan':' worldwide'),loading:'lazy',sandbox:'allow-scripts allow-same-origin allow-popups allow-popups-to-escape-sandbox',referrerpolicy:'strict-origin-when-cross-origin'}))}function o(){var r=C(e,t);a.setAttribute('href',r.explore),a.textContent='',m(a,['Open in Google Trends',' ',v('ext'),f('span',{
class:'sr-only',text:'(opens in a new tab)'})]),s.trendsOn?i():(n.textContent='',n.className='tr-box',m(n,[f('p',null,'See how much people search for ',f('b',{text:'“'+r.kw+'”'}),t?' in Pakistan.':' around the world.'),f('button',{class:'btn sm primary',type:'button','data-trends':'1',onclick:i},'Show Google Trends chart'),f('small',{class:'faint',text:'The chart loads from Google when you click.'
})]))}return o(),f('section',{class:'d-sec trends'},f('div',{class:'tr-head'},f('h3',{text:'Google Trends · last 12 months'}),f('div',{class:'seg',role:'group','aria-label':'Trends region'},r)),n,f('p',{class:'tr-note faint',text:'100 = the busiest week for this search in the year. No line? Too few people search it there, so switch the region.'}),a)}(e),c.length?f('div',{class:'d-info'
},c.map(function(e){return f('div',null,f('h4',{text:e[0]}),f('p',{text:e[1]}))})):null,f('section',{class:'d-sec'},f('h3',{text:'Check it yourself'}),f('div',{class:'links'},l)),f('p',{class:'faint',text:'Prices are AI estimates. Always confirm the real cost with the supplier before you buy stock.'}),f('div',{class:'d-actions'},f('button',{class:'btn sm',type:'button','data-share':e.key
},v('share'),'Share'),I(e,!1),f('span',{class:'spacer'}),f('button',{class:'btn sm icon',type:'button','data-step':'-1','aria-label':'Previous product',disabled:u<=0||null},v('left')),f('button',{class:'btn sm icon',type:'button','data-step':'1','aria-label':'Next product',disabled:u<0||u>=s.view.length-1||null},v('right')))))}function U(e,t){var n=s.byKey[e];if(n&&W){
W.open||(s.lastFocus=document.activeElement);var a=o('#detailInner');a.textContent='',m(a,D(n)),s.current=e,W.open||('function'==typeof W.showModal?W.showModal():W.setAttribute('open',''));var r=o('#detailClose');r&&r.focus(),t||history.replaceState(null,'','#p='+encodeURIComponent(e)),document.title=n.name+' · WinScout'}}function q(){W&&W.open&&W.close()}function K(e){
var t=s.view.findIndex(function(e){return e.key===s.current}),n=s.view[t+e];n&&U(n.key)}function B(){var e=location.hash.match(/^#p=([a-z0-9-]{1,100})$/);e&&s.byKey[e[1]]?U(e[1],!0):W&&W.open&&!e&&q()}function G(e){var t=o('#toast');t.textContent=e,t.classList.add('show'),clearTimeout(F),F=setTimeout(function(){t.classList.remove('show')},2600)}function j(e){var t=String(null==e?'':e)
;return/^[=+\-@\t\r]/.test(t)&&(t='\''+t),/[",\n\r]/.test(t)?'"'+t.replace(/"/g,'""')+'"':t}function H(){s.verdict=s.trend=s.comp=s.proof='all',s.markup=0,s.photo=!1,s.day='latest',s.q='',s.niche='all',s.savedOnly=!1,s.limit=n,['#fVerdict','#fTrend','#fComp','#fProof'].forEach(function(e){o(e).value='all'}),o('#fMarkup').value='0',o('#fPhoto').checked=!1,o('#fDay').value='latest',o('#q').value='',
N()}W&&(W.addEventListener('close',function(){s.current=-1,document.title='WinScout — Winning Product Radar for Global & Pakistan sellers',location.hash&&history.replaceState(null,'',location.pathname+location.search),s.lastFocus&&document.contains(s.lastFocus)&&s.lastFocus.focus()}),W.addEventListener('click',function(e){e.target===W&&q()}),W.addEventListener('keydown',function(e){
if('ArrowRight'===e.key||'ArrowLeft'===e.key){if(/INPUT|TEXTAREA|SELECT/.test(e.target.tagName))return;K('ArrowRight'===e.key?1:-1)}})),document.addEventListener('click',function(e){var t,a,r=e.target.closest('[data-open],[data-save],[data-share],[data-step],[data-niche],[data-clear]');if(r)return r.hasAttribute('data-save')?(t=r.getAttribute('data-save'),
void((a=s.byKey[t])&&(s.saved.has(t)?(s.saved.delete(t),G('Removed from saved')):(s.saved.add(t),G('Saved in this browser')),l('ws-saved',JSON.stringify(Array.from(s.saved).slice(-500))),Array.prototype.forEach.call(document.querySelectorAll('[data-save]'),function(e){if(e.getAttribute('data-save')===t){var n=s.saved.has(t);e.setAttribute('aria-pressed',String(n)),
e.setAttribute('aria-label',(n?'Remove from saved: ':'Save: ')+a.name),e.title=n?'Saved':'Save';var r=e.lastChild;r&&3===r.nodeType&&(r.textContent=n?'Saved':'Save')}}),o('#savedCount').textContent=String(s.saved.size),o('#savedCount').hidden=!s.saved.size,s.savedOnly&&N()))):r.hasAttribute('data-share')?function(e){var t=s.byKey[e];if(t){
var n=location.origin+location.pathname+'#p='+encodeURIComponent(e);navigator.share?navigator.share({title:t.name+' · WinScout',text:'Winning product idea: '+t.name,url:n}).catch(function(){}):navigator.clipboard?navigator.clipboard.writeText(n).then(function(){G('Link copied')},function(){G(n)}):G(n)}
}(r.getAttribute('data-share')):r.hasAttribute('data-step')?K(parseInt(r.getAttribute('data-step'),10)):r.hasAttribute('data-clear')?H():r.hasAttribute('data-niche')?(s.niche=r.getAttribute('data-niche'),s.limit=n,N()):r.hasAttribute('data-open')?U(r.getAttribute('data-open')):void 0}),o('#marketSeg').addEventListener('click',function(e){var t=e.target.closest('button[data-m]')
;t&&(s.market=t.getAttribute('data-m'),s.limit=n,Array.prototype.forEach.call(this.querySelectorAll('button'),function(e){e.setAttribute('aria-pressed',String(e===t))}),N())}),o('#q').addEventListener('input',function(e){clearTimeout(z),z=setTimeout(function(){s.q=e.target.value.slice(0,80),s.limit=n,N()},150)}),o('#sort').addEventListener('change',function(e){s.sort=e.target.value,N()}),
o('#filtersBtn').addEventListener('click',function(){var e=o('#filters');e.hidden=!e.hidden,this.setAttribute('aria-expanded',String(!e.hidden))}),[['#fDay','day'],['#fVerdict','verdict'],['#fTrend','trend'],['#fComp','comp'],['#fProof','proof']].forEach(function(e){o(e[0]).addEventListener('change',function(t){s[e[1]]=t.target.value,s.limit=n,N()})}),
o('#fMarkup').addEventListener('change',function(e){s.markup=parseFloat(e.target.value)||0,s.limit=n,N()}),o('#fPhoto').addEventListener('change',function(e){s.photo=e.target.checked,s.limit=n,N()}),o('#clearBtn').addEventListener('click',H),o('#csvBtn').addEventListener('click',function(){
var e=[['Date','Market','Niche','Product','Score','Verdict','Proof','Cost','Sell price','Currency','Markup','Competition','Trend','Why it wins','Who buys it','Video ad idea','Where to sell','Risk','Search keyword','Supplier link','Source','Image']];s.view.forEach(function(t){e.push([t.date,t.market,t.niche,t.name,t.score,b(t.score).label,{hard:'Sales numbers',popular:'Listed popular',
opinion:'Opinion only'}[t.proof]||'',t.cost,t.price,t.currency,t.markup?t.markup.toFixed(1):'',t.competition,t.trend,t.why,t.audience,t.adIdea,t.whereToSell,t.risk,t.keyword,S(t),t.source||'',t.image||''])});var t=new Blob([String.fromCharCode(65279)+e.map(function(e){return e.map(j).join(',')}).join('\r\n')],{type:'text/csv;charset=utf-8'}),n=f('a',{
download:'winscout-'+(new Date).toISOString().slice(0,10)+'.csv'});n.href=URL.createObjectURL(t),document.body.appendChild(n),n.click(),n.remove(),setTimeout(function(){URL.revokeObjectURL(n.href)},3e3),G('Downloaded '+s.view.length+' products')}),o('#moreBtn').addEventListener('click',function(){var e=s.limit;s.limit+=n,N();var t=document.querySelectorAll('#list .card');if(t[e]){
var a=t[e].querySelector('.title button');a&&a.focus()}}),o('#savedBtn').addEventListener('click',function(){s.savedOnly=!s.savedOnly,s.limit=n,N(),document.getElementById('products').scrollIntoView()}),window.addEventListener('hashchange',B),o('#detailClose').addEventListener('click',q);try{var V=JSON.parse(l('ws-saved')||'[]');Array.isArray(V)&&V.slice(-500).forEach(function(e){
'string'==typeof e&&e.length<120&&s.saved.add(e)})}catch(e){}var $='function'==typeof AbortController?new AbortController:null,J=setTimeout(function(){$&&$.abort()},a);fetch(e+'?v='+Math.floor(Date.now()/6e4),{cache:'no-store',signal:$?$.signal:void 0,credentials:'omit'}).then(function(e){if(!e.ok)throw new Error('HTTP '+e.status);return e.json()}).then(function(e){clearTimeout(J)
;var t=e&&Array.isArray(e.products)?e.products.slice(0,2e3):[],n={};s.all=t.map(g).filter(function(e){return e.name&&e.date}),s.all.forEach(function(e){var t,a=(t=e.date+'-'+e.market+'-'+e.name,String(t).toLowerCase().normalize('NFKD').replace(/[^a-z0-9]+/g,'-').replace(/^-+|-+$/g,'').slice(0,90)||'p');n[a]&&(a=a.slice(0,84)+'-'+e.i),n[a]=1,e.key=a,s.byKey[a]=e}),
s.updated=/^\d{4}-\d{2}-\d{2} \d{2}:\d{2}$/.test(String(e&&e.updated))?e.updated:'';var a=Array.from(new Set(s.all.map(function(e){return e.date}))).sort();s.latest=a[a.length-1]||'';var r=o('#fDay');(a.slice().reverse().forEach(function(e){m(r,f('option',{value:e,text:k(e,!0)}))}),s.latest)&&((Date.now()-new Date(s.latest+'T12:00:00').getTime())/864e5>2.5&&(o('#notice').hidden=!1,
o('#noticeText').textContent='The newest products are from '+k(s.latest,!0)+'. The daily update may be delayed.'));N(),B()}).catch(function(){var e;clearTimeout(J),(e=o('#list')).textContent='',e.classList.remove('list-min'),e.setAttribute('aria-busy','false'),m(e,f('div',{class:'empty',role:'alert'},f('h3',{text:'Products could not load'}),f('p',{class:'muted',
text:'Please check your internet connection and try again.'}),f('button',{class:'btn',type:'button',onclick:function(){location.reload()},text:'Try again'}))),o('#liveText').textContent='Offline',o('#count').textContent=''})}();